/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AVL.Vista;

import inventario.conection.ConexionBase;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SergioCardoza
 */
public class Buscar extends javax.swing.JFrame {

    /**
     * Creacion del Formulario Buscar
     */
    public Buscar() {
        initComponents();
        llenarDatosTipoCarro();
        llenarMarca();
        llenarTabla();
       
    }

    public void llenarDatosTipoCarro() {
        String consulta = "select * from cat_tipo_vehi";
        try {
            Statement sentencia = ConexionBase.obtener().createStatement();
            ResultSet resultado = sentencia.executeQuery(consulta);
            while (resultado.next()) {
                System.out.println(resultado.getObject("tipo_vehiculo"));
                jComboBoxTipo.addItem(resultado.getString("tipo_vehiculo"));
            }
        } catch (Exception e) {
        }
    }

    public void llenarMarca() {
        String consulta = "select * from marca";
        try {
            Statement sentencia = ConexionBase.obtener().createStatement();
            ResultSet resultado = sentencia.executeQuery(consulta);
            while (resultado.next()) {
                System.out.println(resultado.getObject("nombre_marca"));
                jComboBoxMarca.addItem(resultado.getString("nombre_marca"));
            }
        } catch (Exception e) {
        }
    }

    public void llenarTabla() {
        String consulta = "select id_vehiculo,tipo_vehiculo,tipo_motor,nombre_marca,transmision,modelo,precio,año from vehiculo ve\n"
                + "inner join cat_tipo_vehi cat\n"
                + "on ve.id_tipo_vehi = cat.id_tipo_vehi\n"
                + "inner join cat_motor catm\n"
                + "on ve.id_motor = catm.id_motor\n"
                + "inner join marca mar\n"
                + "on ve.id_marca = mar.id_marca";
        try {
            Statement sentencia = ConexionBase.obtener().createStatement();
            ResultSet resultado = sentencia.executeQuery(consulta);
            String[] columnNames = {"CODIGO", "Tipo Vehiculo", "Motor", "Marca", "Transmision", "Modelo", "Precio", "Año"};

            DefaultTableModel tableModel = (DefaultTableModel) jTableDatos.getModel();
            tableModel.setColumnIdentifiers(columnNames);
            tableModel.setRowCount(0);
            java.sql.ResultSetMetaData rsmd = resultado.getMetaData();
            int colNo = rsmd.getColumnCount();
            while (resultado.next()) {
                Object[] objects = new Object[colNo];
                for (int i = 0; i < colNo; i++) {
                    objects[i] = resultado.getObject(i + 1);
                }
                tableModel.addRow(objects);
            }
            jTableDatos.setModel(tableModel);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextValor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        Buscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("InfoInvetarioCarros"); // NOI18N
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Dato Vehiculo");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, 20));
        getContentPane().add(jTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 198, 850, 260));

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 180, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Ingresar Vehiculo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 180, -1));
        jButton2.getAccessibleContext().setAccessibleName("Ingrear vehiculo ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Marca:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        getContentPane().add(jComboBoxMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 150, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Tipo: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, -1, -1));

        getContentPane().add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, 150, 30));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Modificar datos ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 480, 180, -1));

        Buscar.setBackground(new java.awt.Color(0, 153, 153));
        Buscar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AVL/Vista/Captura-removebg-preview.png"))); // NOI18N
        jLabel1.setText(" ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Registro registro = new Registro();
            registro.setVisible(true);
            this.dispose();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
        System.out.println("AVL.Vista.Buscar.BuscarActionPerformed()");
        String modelo = jTextValor.getText();
        String marca = jComboBoxMarca.getSelectedItem().toString();
        String tipo = jComboBoxTipo.getSelectedItem().toString();
        String consulta = "select id_vehiculo,tipo_vehiculo,tipo_motor,nombre_marca,transmision,modelo,precio,año from vehiculo ve\n" +
            "inner join cat_tipo_vehi cat on ve.id_tipo_vehi = cat.id_tipo_vehi \n" +
            "inner join cat_motor catm on ve.id_motor = catm.id_motor\n" +
            "inner join marca mar on ve.id_marca = mar.id_marca\n" +
            "where  modelo like '"+modelo+"%' or nombre_marca='"+marca+"' or tipo_vehiculo='"+tipo+"'";
        try {
            Statement sentencia = ConexionBase.obtener().createStatement();
            ResultSet resultado = sentencia.executeQuery(consulta);
            String[] columnNames = {"CODIGO", "Tipo Vehiculo", "Motor", "Marca", "Transmision", "Modelo", "Precio", "Año"};

            DefaultTableModel tableModel = (DefaultTableModel) jTableDatos.getModel();
            tableModel.setColumnIdentifiers(columnNames);
            tableModel.setRowCount(0);
            java.sql.ResultSetMetaData rsmd = resultado.getMetaData();
            int colNo = rsmd.getColumnCount();
            while (resultado.next()) {
                Object[] objects = new Object[colNo];
                for (int i = 0; i < colNo; i++) {
                    objects[i] = resultado.getObject(i + 1);
                    System.out.println("datos == "+resultado.getObject(i + 1));
                }
                tableModel.addRow(objects);
            }
            jTableDatos.setModel(tableModel);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JTextField jTextValor;
    // End of variables declaration//GEN-END:variables
}
